-- 코드를 입력하세요
WITH CTE AS (
    SELECT I.ANIMAL_ID, DATEDIFF(O.DATETIME, I.DATETIME) AS DIFF
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DIFF DESC
    LIMIT 2)
    
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN CTE C
    ON I.ANIMAL_ID = C.ANIMAL_ID