-- 코드를 입력하세요
WITH CTE AS (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING CNT >= 3)
    
SELECT U.USER_ID, 
       U.NICKNAME, 
       CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS `전체주소`, 
       CONCAT('010-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS `전화번호`
FROM USED_GOODS_USER U
JOIN CTE C
    ON U.USER_ID = C.WRITER_ID
ORDER BY U.USER_ID DESC