-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT F.FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL
      FROM FIRST_HALF F, JULY J
      WHERE F.FLAVOR = J.FLAVOR
      GROUP BY F.FLAVOR
      ORDER BY TOTAL DESC
      LIMIT 3) FJ
      ON F.FLAVOR = FJ.FLAVOR
GROUP BY F.FLAVOR
ORDER BY FJ.TOTAL ASC