-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION
    SELECT NUM + 1
    FROM CTE
    WHERE NUM < 23
)

SELECT CTE_NUM.NUM AS HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT JOIN CTE AS CTE_NUM
    ON CTE_NUM.NUM = HOUR(A.DATETIME)
GROUP BY HOUR