-- 코드를 입력하세요
WITH CTE AS (
    SELECT VIEWS, BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1)
    
SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
JOIN CTE C
    ON F.BOARD_ID = C.BOARD_ID
ORDER BY F.FILE_ID DESC